const types = {
  UPDATE_SEARCH_PARAM: "UPDATE_SEARCH_PARAM",
  UPDATE_COUNTRY_CODE: "UPDATE_COUNTRY_CODE",
  FETCH_JOB_DATA: "FETCH_JOB_DATA",
  FETCH_USER_LOCATION: "FETCH_USER_LOCATION",
  LOAD_JOBS: "LOAD_JOBS",
  SORT_BY_DATE: "SORT_BY_DATE",
  GET_UNSORTED_DATA: "GET_UNSORTED_DATA",
  TURN_ON_FILTER: "TURN_ON_FILTER",
  TURN_OFF_FILTER: "TURN_OFF_FILTER",
};

export default types;
