const types = {
  UPDATE_SEARCH_PARAM: "UPDATE_SEARCH_PARAM",
  UPDATE_ALL_SEARCH_PARAMS: "UPDATE_ALL_SEARCH_PARAMS",
  UPDATE_COUNTRY_CODE: "UPDATE_COUNTRY_CODE",
  FETCH_JOB_DATA: "FETCH_JOB_DATA",
  FETCH_USER_LOCATION: "FETCH_USER_LOCATION",
  LOAD_JOBS: "LOAD_JOBS",
  SORT_BY_DATE: "SORT_BY_DATE",
  SORT_BY_MAX_SALARY: "SORT_BY_MAX_SALARY",
  GET_UNSORTED_JOB_DATA: "GET_UNSORTED_JOB_DATA",
  TURN_ON_FILTER: "TURN_ON_FILTER",
  TURN_OFF_FILTER: "TURN_OFF_FILTER",
  SELECT_JOB: "SELECT_JOB",
  CLEAR_JOB_SELECTED: "CLEAR_JOB_SELECTED",
};

export default types;
