const types = {
  UPDATE_SEARCH_PARAM: "UPDATE_SEARCH_PARAM",
  UPDATE_COUNTRY_CODE: "UPDATE_COUNTRY_CODE",
  FETCH_JOB_DATA: "FETCH_JOB_DATA",
  FETCH_USER_LOCATION: "FETCH_USER_LOCATION",
};

export default types;
